name:                rtiow
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/rtiow#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
- MultiWayIf

ghc-options:
- -Wall

dependencies:
  - base >= 4.7 && < 5
  - mtl 
  - random
  - gloss
  - bytestring
  #- lens 

executables:
  rtiow:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N